### ISSUE TITLE
no results

### ISSUE THREAD

**Issue by UserScripts0815** [amsbr/OctoPrint-Stats#17]
in spite of the values ​​entered, the graphs remain empty for me. what can this be?

**Comment by schnello** [comment]
Same here. Octopi on a Ubuntu machine with Klipper FW
![image](https://user-images.githubusercontent.com/6481341/62350368-ce775580-b502-11e9-83ba-7d44b4fa75c3.png)

2019-08-02 08:57:49,856 - octoprint.plugin - ERROR - Error while calling plugin stats
Traceback (most recent call last):
  File "/home/nas/OctoPrint/venv/local/lib/python2.7/site-packages/octoprint/plugin/__init__.py", line 219, in call_plugin
    result = getattr(plugin, method)(*args, **kwargs)
  File "/home/nas/OctoPrint/venv/local/lib/python2.7/site-packages/octoprint_stats/__init__.py", line 710, in on_event
    self.statDB.execute(sql)
AttributeError: 'StatsPlugin' object has no attribute 'statDB'

**Comment by josulf** [comment]
I have exactly the same problem. Any hint to fix it?

**Comment by amsbr** [comment]
I go to deploy new version in next days and correct issues.

**Comment by schnello** [comment]
Thanks. With the latest release it works:
![image](https://user-images.githubusercontent.com/6481341/64131677-7dd96d80-cdca-11e9-94f1-4da7473e9b02.png)
